package com.example.devicesync.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF006B5B)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFA6F2DE)
val LightOnPrimaryContainer = Color(0xFF00201A)
val LightSecondary = Color(0xFF4B625B)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightBackground = Color(0xFFF6FAF8)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFE8F0ED)
val LightOnSurface = Color(0xFF15201D)
val LightOnSurfaceVariant = Color(0xFF4B625B)
val LightOutline = Color(0xFF70817C)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)

val DarkPrimary = Color(0xFF8BD8C4)
val DarkOnPrimary = Color(0xFF00382F)
val DarkPrimaryContainer = Color(0xFF005145)
val DarkOnPrimaryContainer = Color(0xFFA6F2DE)
val DarkSecondary = Color(0xFFB7C9C3)
val DarkOnSecondary = Color(0xFF22352F)
val DarkBackground = Color(0xFF101513)
val DarkSurface = Color(0xFF18201D)
val DarkSurfaceVariant = Color(0xFF25302C)
val DarkOnSurface = Color(0xFFE4ECE8)
val DarkOnSurfaceVariant = Color(0xFFB7C9C3)
val DarkOutline = Color(0xFF899B95)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)

val HighContrastPrimary = Color(0xFF00FFFF)
val HighContrastOnPrimary = Color(0xFF000000)
val HighContrastBackground = Color(0xFF000000)
val HighContrastSurface = Color(0xFF000000)
val HighContrastSurfaceVariant = Color(0xFF1A1A1A)
val HighContrastOnSurface = Color(0xFFFFFFFF)
val HighContrastOutline = Color(0xFFFFFFFF)
val HighContrastError = Color(0xFFFF4D4D)

val StatusConnected = Color(0xFF18794E)
val StatusSyncing = Color(0xFF9A6500)
val StatusConnecting = StatusSyncing
val StatusOffline = Color(0xFF5E6C68)
val StatusError = Color(0xFFBA1A1A)
val StatusAttention = Color(0xFF8A4F00)

val DarkStatusConnected = Color(0xFF66D69E)
val DarkStatusSyncing = Color(0xFFF4C95D)
val DarkStatusOffline = Color(0xFFAAB8B3)
val DarkStatusError = Color(0xFFFFB4AB)
val DarkStatusAttention = Color(0xFFFFB86B)
